package ventana;

import enemigo.Armada;
import enemigo.Tanque;
import java.awt.GridLayout;
import javax.swing.JButton;
import movimiento.Funcion;
import prolog.Conexion;

public class Juego1 extends javax.swing.JInternalFrame {
    private String nombreTanque1;
    private String nombreTanque2;
    private String nombreTanque3;
    private int cantidadMovimientoTanque1;
    private int cantidadMovimientoTanque2;
    private int cantidadMovimientoTanque3;
    private String [][]matrizJuego1 ={{"X", "f","X","X","g", "f1", "X","X", "h", "X"},
                {"X", "b2","X","X","e2", "f2", "X","X", "i2", "X"},
                {"a3", "b3","c3","d3","e3", "f3", "g3","h3", "i3", "j3"},
                {"a4", "b4","c4","d4","e4", "f4", "g4","h4", "i4", "j4"},
                {"a5", "b5","c5","d5","e5", "f5", "g5","h5", "i5", "t"}};
    
    private String [][]matrizOriginalJuego1 ={{"X", "f","X","X","g", "f1", "X","X", "h", "X"},
                {"X", "b2","X","X","e2", "f2", "X","X", "i2", "X"},
                {"a3", "b3","c3","d3","e3", "f3", "g3","h3", "i3", "j3"},
                {"a4", "b4","c4","d4","e4", "f4", "g4","h4", "i4", "j4"},
                {"a5", "b5","c5","d5","e5", "f5", "g5","h5", "i5", "j5"}};
    
    private JButton[][] matrizBotones;
    
    public Juego1() {
        Armada laArmada = new Armada();
        laArmada.agregarTanque(new Tanque("facil","a",1));
        laArmada.agregarTanque(new Tanque("medio","b",2));
        laArmada.agregarTanque(new Tanque("dificil","c",3));
        
        nombreTanque1=laArmada.buscarNombre("facil");
        nombreTanque2=laArmada.buscarNombre("medio");
        nombreTanque3=laArmada.buscarNombre("dificil");
        
        cantidadMovimientoTanque1=laArmada.buscarCantidadMovimiento(nombreTanque1);
        cantidadMovimientoTanque2=laArmada.buscarCantidadMovimiento(nombreTanque2);
        cantidadMovimientoTanque3=laArmada.buscarCantidadMovimiento(nombreTanque3);
        
        matrizJuego1[2][1]=nombreTanque3;
        matrizJuego1[2][4]=nombreTanque2;
        matrizJuego1[2][8]=nombreTanque1;
        
        int cantidadFilas=Funcion.buscarFilaColumnaCantidad(matrizJuego1,0);
        int cantidadColumnas=Funcion.buscarFilaColumnaCantidad(matrizJuego1,1);
        
        matrizBotones = new JButton[cantidadFilas][cantidadColumnas];
        initComponents();
        Conexion.crearConectadosProlog(matrizOriginalJuego1);
        
        panelBoton.setLayout(new GridLayout(cantidadFilas,cantidadColumnas));
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        textoMatriz.setVisible(false);
    }
    
    public static void nuevoTextoVida(String texto){
       labelCantidadVidas.setText(texto);
    }
    
    public static void nuevoTextoEdificiosDestruidos(String texto){
       labelCantidadEdificiosDestruidos.setText(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonArribaM = new javax.swing.JButton();
        botonIzquierdaM = new javax.swing.JButton();
        botonDerechaM = new javax.swing.JButton();
        botonAbajoM = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonArribaM1 = new javax.swing.JButton();
        botonIzquierdaM1 = new javax.swing.JButton();
        botonDerechaM1 = new javax.swing.JButton();
        botonAbajoM1 = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        labelCantidadEdificiosDestruidos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelCantidadVidas = new javax.swing.JLabel();
        panelBoton = new javax.swing.JPanel();
        textoMatriz = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        labelCantidadEdificiosRestantes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelMovimientosArmada = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelCantidadTanquesArmada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Moverse");

        botonArribaM.setText("🡹");
        botonArribaM.setActionCommand("botonArribaM");
        botonArribaM.setEnabled(false);
        botonArribaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaMActionPerformed(evt);
            }
        });

        botonIzquierdaM.setText("🡸");
        botonIzquierdaM.setActionCommand("botonIzquierdaM");
        botonIzquierdaM.setEnabled(false);
        botonIzquierdaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaMActionPerformed(evt);
            }
        });

        botonDerechaM.setText("🡺");
        botonDerechaM.setActionCommand("botonDerechaM");
        botonDerechaM.setEnabled(false);
        botonDerechaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaMActionPerformed(evt);
            }
        });

        botonAbajoM.setText("🡻");
        botonAbajoM.setActionCommand("botonAbajoM");
        botonAbajoM.setEnabled(false);
        botonAbajoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botonIzquierdaM)
                .addGap(18, 18, 18)
                .addComponent(botonDerechaM)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonArribaM)
                    .addComponent(botonAbajoM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(botonArribaM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIzquierdaM)
                    .addComponent(botonDerechaM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(botonAbajoM))
        );

        jLabel2.setText("Disparar");

        botonArribaM1.setText("🡹");
        botonArribaM1.setActionCommand("botonArribaM");
        botonArribaM1.setEnabled(false);
        botonArribaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArribaM1ActionPerformed(evt);
            }
        });

        botonIzquierdaM1.setText("🡸");
        botonIzquierdaM1.setActionCommand("botonIzquierdaM");
        botonIzquierdaM1.setEnabled(false);
        botonIzquierdaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIzquierdaM1ActionPerformed(evt);
            }
        });

        botonDerechaM1.setText("🡺");
        botonDerechaM1.setActionCommand("botonDerechaM");
        botonDerechaM1.setEnabled(false);
        botonDerechaM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDerechaM1ActionPerformed(evt);
            }
        });

        botonAbajoM1.setText("🡻");
        botonAbajoM1.setActionCommand("botonAbajoM");
        botonAbajoM1.setEnabled(false);
        botonAbajoM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbajoM1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(botonIzquierdaM1)
                .addGap(18, 18, 18)
                .addComponent(botonDerechaM1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonArribaM1)
                    .addComponent(botonAbajoM1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(botonArribaM1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonIzquierdaM1)
                    .addComponent(botonDerechaM1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(botonAbajoM1))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel3.setText("Edificios destruidos:");

        labelCantidadEdificiosDestruidos.setText("0");

        jLabel4.setText("Vida:");

        labelCantidadVidas.setText("3");

        panelBoton.setLayout(new java.awt.GridLayout(1, 0));

        textoMatriz.setEditable(false);
        textoMatriz.setColumns(20);
        textoMatriz.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoMatriz.setRows(5);
        textoMatriz.setToolTipText("");
        textoMatriz.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("Edificios restantes:");

        labelCantidadEdificiosRestantes.setText("3");

        jLabel6.setText("Movimientos llamada armada:");

        labelMovimientosArmada.setText("3");

        jLabel7.setText("Tanques armada restantes:");

        labelCantidadTanquesArmada.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCantidadEdificiosDestruidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCantidadEdificiosRestantes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMovimientosArmada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCantidadTanquesArmada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCantidadVidas)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addComponent(textoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(labelCantidadEdificiosDestruidos))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(labelCantidadEdificiosRestantes))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(labelMovimientosArmada))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(labelCantidadTanquesArmada))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(labelCantidadVidas))))
                    .addComponent(textoMatriz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(botonSalir)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        Inicio.activarBoton();
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonArribaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaMActionPerformed
        // TODO add your handling code here:
        Funcion.realizarMovimientoBotones(matrizJuego1,"t",2,botonAbajoM,botonArribaM,botonDerechaM,botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,1,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
    }//GEN-LAST:event_botonArribaMActionPerformed

    private void botonAbajoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoMActionPerformed
        // TODO add your handling code here:
        Funcion.realizarMovimientoBotones(matrizJuego1,"t",1,botonAbajoM,botonArribaM,botonDerechaM,botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,1,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
    }//GEN-LAST:event_botonAbajoMActionPerformed

    private void botonIzquierdaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaMActionPerformed
        // TODO add your handling code here:
        Funcion.realizarMovimientoBotones(matrizJuego1,"t",4,botonAbajoM,botonArribaM,botonDerechaM,botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,1,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
    }//GEN-LAST:event_botonIzquierdaMActionPerformed

    private void botonDerechaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaMActionPerformed
        // TODO add your handling code here:
        Funcion.realizarMovimientoBotones(matrizJuego1,"t",3,botonAbajoM,botonArribaM,botonDerechaM,botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,1,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
    }//GEN-LAST:event_botonDerechaMActionPerformed

    private void botonArribaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArribaM1ActionPerformed
        // TODO add your handling code here:
        Funcion.realizarDisparoBotones(matrizJuego1,"t",2,botonAbajoM1,botonArribaM1,botonDerechaM1,botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,0,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
        
    }//GEN-LAST:event_botonArribaM1ActionPerformed

    private void botonAbajoM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbajoM1ActionPerformed
        // TODO add your handling code here:
        Funcion.realizarDisparoBotones(matrizJuego1,"t",1,botonAbajoM1,botonArribaM1,botonDerechaM1,botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,0,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
        
    }//GEN-LAST:event_botonAbajoM1ActionPerformed

    private void botonIzquierdaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIzquierdaM1ActionPerformed
        // TODO add your handling code here:
        Funcion.realizarDisparoBotones(matrizJuego1,"t",4,botonAbajoM1,botonArribaM1,botonDerechaM1,botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,0,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
        
    }//GEN-LAST:event_botonIzquierdaM1ActionPerformed

    private void botonDerechaM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDerechaM1ActionPerformed
        // TODO add your handling code here:
        Funcion.realizarDisparoBotones(matrizJuego1,"t",3,botonAbajoM1,botonArribaM1,botonDerechaM1,botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.desactivarBotones(botonAbajoM,botonArribaM,botonIzquierdaM,botonDerechaM);
        Funcion.desactivarBotones(botonAbajoM1,botonArribaM1,botonIzquierdaM1,botonDerechaM1);
        Funcion.actualizarLabelMovimientoArmada(matrizJuego1, matrizOriginalJuego1, nombreTanque1,nombreTanque2,nombreTanque3,
                cantidadMovimientoTanque1,cantidadMovimientoTanque2,cantidadMovimientoTanque3,
                labelCantidadEdificiosDestruidos, labelCantidadEdificiosRestantes, labelMovimientosArmada, labelCantidadTanquesArmada,
                labelCantidadVidas,0,1,this);
        Funcion.revisarMovimientosValidosBotones(matrizJuego1, "t",botonAbajoM, botonArribaM, botonDerechaM, botonIzquierdaM,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.revisarDisparosValidosBotones(matrizJuego1, "t", botonAbajoM1, botonArribaM1, botonDerechaM1, botonIzquierdaM1,nombreTanque1,nombreTanque2,nombreTanque3);
        Funcion.matrizBotones(matrizJuego1, matrizBotones, panelBoton, nombreTanque1, nombreTanque2, nombreTanque3);
        textoMatriz.setText(Funcion.imprimirMatriz(matrizJuego1));
        
    }//GEN-LAST:event_botonDerechaM1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbajoM;
    private javax.swing.JButton botonAbajoM1;
    private javax.swing.JButton botonArribaM;
    private javax.swing.JButton botonArribaM1;
    private javax.swing.JButton botonDerechaM;
    private javax.swing.JButton botonDerechaM1;
    private javax.swing.JButton botonIzquierdaM;
    private javax.swing.JButton botonIzquierdaM1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel labelCantidadEdificiosDestruidos;
    private javax.swing.JLabel labelCantidadEdificiosRestantes;
    private javax.swing.JLabel labelCantidadTanquesArmada;
    public static javax.swing.JLabel labelCantidadVidas;
    private javax.swing.JLabel labelMovimientosArmada;
    private javax.swing.JPanel panelBoton;
    private javax.swing.JTextArea textoMatriz;
    // End of variables declaration//GEN-END:variables
}
